version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    environment:
      DISPLAY:
    volumes:
      - ../../src:/usr/local/src/siberrisk
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["python3", "main.py"]
  web:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../src:/usr/local/src/siberrisk
  python:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    volumes:
      - ../../src:/usr/local/src/siberrisk
    entrypoint: [ "python3" ]
