version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    environment:
      DISPLAY:
    volumes:
      - ../../src:/usr/local/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["python3", "main.py"]
    depends_on:
      - pyrjmcmc
  web:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    working_dir: /usr/local/src/websites
    ports:
      - "5006:5006"
    volumes:
      - ../../src:/usr/local/src
    command: ["bokeh", "serve", "StrongMotionDatabase", "--allow-websocket-origin=*"]
    depends_on:
      - seismic
  python:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    volumes:
      - ../../src:/usr/local/src
    entrypoint: [ "python3" ]
  pyrjmcmc:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    volumes:
      - ../../src:/usr/local/src
    working_dir: /usr/local/src/lib/pyrjmcmc
    command: ["python3", "setup.py", "build_ext", "--inplace"]
  seismic:
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    volumes:
      - ../../src:/usr/local/src
    working_dir: /usr/local/src/lib
    command: ["python3", "setup.py", "build_ext", "--inplace"]
