services:
  app:
    image: siberrisk
    environment:
      DISPLAY:
    volumes:
      - ../../src:/usr/local/src
      - ../../data:/usr/local/data
      - ../../draft:/usr/local/draft
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["python3", "main.py"]
    depends_on:
      - pyrjmcmc
  web:
    image: siberrisk
    working_dir: /usr/local/src/websites
    ports:
      - "5006:5006"
    volumes:
      - ../../src:/usr/local/src
      - ../../data:/usr/local/data
      - ../../draft:/usr/local/draft
      - ../../src/websites/StrongMotionDatabase/static/images:/opt/conda/lib/python3.12/site-packages/bokeh/server/static/images
    command: ["bokeh", "serve", "StrongMotionDatabase/home.py", "StrongMotionDatabase/downloadManager.py", "--allow-websocket-origin=*", "--index=/usr/local/src/websites/StrongMotionDatabase/templates/index.html", "--prefix=StrongMotionDatabase", "--args", "http://localhost:5006/"]
    depends_on:
      - seismic
  python:
    image: siberrisk
    build:
      context: .
      dockerfile: siberrisk.Dockerfile
    volumes:
      - ../../src:/usr/local/src
    entrypoint: [ "python3" ]
  pyrjmcmc:
    image: siberrisk
    volumes:
      - ../../src:/usr/local/src
    working_dir: /usr/local/src/lib/pyrjmcmc
    command: ["python3", "setup.py", "build_ext", "--inplace"]
    depends_on:
      - python
  seismic:
    image: siberrisk
    volumes:
      - ../../src:/usr/local/src
    working_dir: /usr/local/src/lib
    command: ["python3", "setup.py", "build_ext", "--inplace"]
    depends_on:
      - python
