name: Tag Issue on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  tag-issue:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Add label to linked issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extrae la descripción del PR
          pr_body="${{ github.event.pull_request.body }}"
          # Busca números de issues referenciados con la sintaxis #123
          issues=$(echo "$pr_body" | grep -oE "#[0-9]+" | tr -d "#")
          
          for issue in $issues; do
            curl -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$issue/labels \
              -d '{"labels":["pending deployment"]}'
          done
